const $=s=>document.querySelector(s),NS='http://www.w3.org/2000/svg';
const names={fable:'Claude Fable 5.1',astra:'GPT-6 Astra',gemini_flash:'Gemini 3.8 Flash',gemini37_flash:'Gemini 3.7 Flash',muse:'Muse Spark 1.3',muse12:'Muse Spark 1.2',grok46:'Grok 4.6',opus:'Claude Opus 5',sol:'GPT-5.6 Sol',luna:'GPT-5.6 Luna',glm:'GLM 5.3 Flash',glm53:'GLM 5.3',kimi_k3:'Kimi K3','fable-5.1':'Claude Fable 5.1','claude-fable-5.1':'Claude Fable 5.1','gpt-6-astra':'GPT-6 Astra','gemini-3.8-flash':'Gemini 3.8 Flash','gemini-3.7-flash':'Gemini 3.7 Flash','muse-spark-1.3':'Muse Spark 1.3','muse-spark-1.2':'Muse Spark 1.2','grok-4.6':'Grok 4.6','opus-5':'Claude Opus 5','claude-opus-5':'Claude Opus 5','gpt-5.6-sol':'GPT-5.6 Sol','gpt-5.6-luna':'GPT-5.6 Luna','glm-5.3':'GLM 5.3','glm-5.3-flash':'GLM 5.3 Flash','kimi-k3':'Kimi K3',claude_code:'Claude Code',codex:'Codex'};
const logos={fable:'anthropic',opus:'anthropic',astra:'openai',sol:'openai',luna:'openai',gemini_flash:'gemini',gemini37_flash:'gemini',muse:'meta',muse12:'meta',grok46:'xai',glm:'zai',glm53:'zai',kimi_k3:'moonshot','fable-5.1':'anthropic','claude-fable-5.1':'anthropic','opus-5':'anthropic','claude-opus-5':'anthropic','gpt-6-astra':'openai','gpt-5.6-sol':'openai','gpt-5.6-luna':'openai','gemini-3.8-flash':'gemini','gemini-3.7-flash':'gemini','muse-spark-1.3':'meta','muse-spark-1.2':'meta','grok-4.6':'xai','glm-5.3':'zai','glm-5.3-flash':'zai','kimi-k3':'moonshot'};
const canonical=new Set(['claude-fable-5.1','gpt-6-astra','gemini-3.8-flash','gemini-3.7-flash','muse-spark-1.3','muse-spark-1.2','grok-4.6','claude-opus-5','gpt-5.6-sol','gpt-5.6-luna','glm-5.3','glm-5.3-flash','kimi-k3']);
const modelOrder=['claude-fable-5.1','claude-opus-5','gpt-6-astra','gpt-5.6-sol','gpt-5.6-luna','muse-spark-1.3','muse-spark-1.2','gemini-3.8-flash','gemini-3.7-flash','grok-4.6','glm-5.3','glm-5.3-flash','kimi-k3'];
const label=x=>names[x]||String(x).replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const el=(tag,attrs={})=>{const n=document.createElementNS(NS,tag);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,v));return n};
const addText=(svg,x,y,t,c='svg-label',anchor='start')=>{const n=el('text',{x,y,class:c,'text-anchor':anchor});n.textContent=t;svg.append(n);return n};
const fmt=n=>new Intl.NumberFormat('en-US').format(n||0);

function heroMesh(){const svg=$('#heroMesh');for(let i=0;i<=12;i++){svg.append(el('path',{d:`M ${70+i*23} ${185-i*13} L ${350+i*23} ${347-i*13}`,class:'mesh-grid'}));svg.append(el('path',{d:`M ${70+i*23} ${185+i*13} L ${350+i*23} ${23+i*13}`,class:'mesh-grid'}))}const pts=[];for(let i=0;i<=26;i++){const x=155+i*13,y=310-i*7-92*Math.exp(-Math.pow((i-14)/5.5,2))+18*Math.sin(i*.55);pts.push(`${x},${y}`)}svg.append(el('polygon',{points:`155,310 ${pts.join(' ')} 493,127 493,170 155,353`,class:'mesh-wave'}));for(let k=1;k<6;k++){const d=pts.map((p,i)=>{const [x,y]=p.split(',').map(Number);return`${i?'L':'M'} ${x} ${y+k*7}`}).join(' ');svg.append(el('path',{d,class:'mesh-contour'}))}}

function attentionChart(models){const svg=$('#attentionChart'),left=58,base=420,shown=models.filter(d=>logos[d.model]&&d.raw_query_matches>0),max=Math.max(1,...shown.map(d=>d.raw_query_matches)),bw=108,gap=27,W=Math.max(1180,left+shown.length*(bw+gap)+34);svg.setAttribute('viewBox',`0 0 ${W} 600`);svg.style.width=`${W}px`;svg.innerHTML='<defs><pattern id="stripe" width="7" height="7" patternUnits="userSpaceOnUse" patternTransform="rotate(45)"><line x1="0" y1="0" x2="0" y2="7" stroke="#f2f2ed" stroke-width="2"/></pattern></defs>';[0,.25,.5,.75,1].forEach(v=>{const y=base-v*300;svg.append(el('line',{x1:left,y1:y,x2:W-24,y2:y,class:'svg-grid'}));addText(svg,left-12,y+4,fmt(Math.round(max*v)),'svg-axis','end')});shown.forEach((d,i)=>{const x=left+18+i*(bw+gap),h=d.raw_query_matches/max*300,delta=d.latest_24h_change_pct;svg.append(el('rect',{x,y:base-h,width:bw,height:h,class:i===0?'attention-bar':'attention-outline'}));addText(svg,x+bw/2,base-h-12,fmt(d.raw_query_matches),'svg-value','middle');svg.append(el('image',{href:`https://unpkg.com/@lobehub/icons-static-svg@latest/icons/${logos[d.model]}.svg`,x:x+bw/2-14,y:base+18,width:28,height:28,class:'company-logo'}));const words=label(d.model).split(' '),cut=Math.ceil(words.length/2),lines=[words.slice(0,cut).join(' '),words.slice(cut).join(' ')].filter(Boolean);lines.forEach((line,j)=>addText(svg,x+bw/2,base+65+j*17,line,'svg-label','middle'));addText(svg,x+bw/2,base+108,delta==null?'24h —':`24h ${delta>0?'+':''}${delta}%`,delta==null?'svg-delta neutral':delta<0?'svg-delta down':'svg-delta','middle')})}

function hourlyChart(models,counts){const svg=$('#hourlyChart'),left=60,right=1145,top=50,base=310;svg.innerHTML='';const series=models.map(m=>({name:label(m.model),data:(counts[m.model]?.data||[]).map(d=>d.tweet_count)}));const max=Math.max(1,...series.flatMap(s=>s.data));[0,.25,.5,.75,1].forEach(v=>{const y=base-v*(base-top);svg.append(el('line',{x1:left,y1:y,x2:right,y2:y,class:'svg-grid'}));addText(svg,left-12,y+4,Math.round(max*v),'svg-axis','end')});series.forEach((s,si)=>{const n=s.data.length||1,d=s.data.map((v,i)=>`${i?'L':'M'} ${left+i*(right-left)/(n-1||1)} ${base-v/max*(base-top)}`).join(' ');svg.append(el('path',{d,class:`hour-line alt${si}`}));const lx=left+si*205;svg.append(el('line',{x1:lx,y1:355,x2:lx+34,y2:355,class:`hour-line alt${si}`}));addText(svg,lx+43,359,s.name,'legend-text')});for(let h=0;h<=24;h+=4)addText(svg,left+h/24*(right-left),base+26,`${String(h).padStart(2,'0')}:00`,'svg-axis','middle')}

function sentiment(models){const root=$('#sentimentRows');root.innerHTML='';const list=[...(models||[])],score=m=>m.clean_directional?.net_sentiment??-9,size=m=>m.clean_directional?.n||0;list.sort((a,b)=>score(b)-score(a)||size(b)-size(a));list.forEach(m=>{const c=m.clean_directional||{},tot=c.n||0;if(!tot)return;const stages=m.stages||{},stageParts=[['reception','reception'],['anticipation','anticipation'],['early_access','early access']].filter(([k])=>stages[k]).map(([k,v])=>`${stages[k]} ${v}`),delta=m.latest_24h_delta_points,deltaClass=delta==null||delta===0?'neutral':delta>0?'positive':'negative',row=document.createElement('div');row.className='sentiment-row';row.innerHTML=`<div class="sentiment-name"><strong>${label(m.model)}</strong><small>${tot} expressed · ${stageParts.join(' / ')||'stage unspecified'}</small></div><div class="sentiment-main"><div class="stack" aria-label="${c.positive} positive, ${c.mixed} mixed, ${c.negative} negative"><span class="positive" style="width:${c.positive/tot*100}%"></span><span class="mixed" style="width:${c.mixed/tot*100}%"></span><span class="negative" style="width:${c.negative/tot*100}%"></span></div><div class="metric-tail ${deltaClass}">${delta==null?'—':`${delta>0?'+':''}${delta}`}</div></div>`;root.append(row)})}

function preferenceRatings(rows){const root=$('#ratingChart');if(!rows?.length){root.innerHTML='<div class="evidence-empty">Not enough connected comparisons.</div>';return}const lo=Math.min(...rows.map(r=>r.low_95)),hi=Math.max(...rows.map(r=>r.high_95)),span=Math.max(1,hi-lo);root.innerHTML=rows.map(r=>{const l=(r.low_95-lo)/span*100,w=(r.high_95-r.low_95)/span*100,m=(r.rating-lo)/span*100,icon=`https://unpkg.com/@lobehub/icons-static-svg@latest/icons/${logos[r.model]||'openai'}.svg`;return`<div class="rating-row"><div class="rating-name"><img src="${icon}" alt=""><span>${label(r.model)}</span></div><div class="rating-range" aria-label="${r.rating}; interval ${r.low_95} to ${r.high_95}"><i style="left:${l}%;width:${w}%"></i><b style="left:${m}%"></b></div><strong class="rating-score">${r.rating}</strong></div>`}).join('')}

function battles(items,ratings){const root=$('#battleList'),total=items.reduce((sum,b)=>sum+(b.n||0),0),byPair=new Map(items.map(b=>[[...b.models].sort().join('|'),b]));$('#ratingCount').textContent=total;$('#ratingMatchups').textContent=items.length;const icon=k=>`https://unpkg.com/@lobehub/icons-static-svg@latest/icons/${logos[k]||'openai'}.svg`,head=modelOrder.map(m=>`<th><span class="matrix-col"><img src="${icon(m)}" alt="">${label(m)}</span></th>`).join(''),rows=modelOrder.map(row=>`<tr><th><span class="matrix-row"><img src="${icon(row)}" alt="">${label(row)}</span></th>${modelOrder.map(col=>{if(row===col)return'<td class="matrix-diagonal"></td>';const b=byPair.get([row,col].sort().join('|'));if(!b)return'<td class="matrix-empty">·</td>';const w=b.votes?.[row]||0,l=b.votes?.[col]||0,n=w+l,share=n?w/n:.5,kind=w===l?'tie':w>l?'lead':'trail',strength=Math.min(.28,.04+n*.018),ids=(b.evidence_ids||[]).join(',');return`<td><button class="matrix-cell ${kind}" style="--strength:${strength}" data-evidence="${ids}" aria-label="${label(row)} ${w}, ${label(col)} ${l}"><b>${w}–${l}</b><small>${Math.round(share*100)}% · n${n}</small></button></td>`}).join('')}</tr>`).join('');root.innerHTML=`<table class="battle-matrix"><thead><tr><th>row model</th>${head}</tr></thead><tbody>${rows}</tbody></table>`;root.onclick=e=>{const cell=e.target.closest('.matrix-cell');if(!cell)return;const ids=new Set(cell.dataset.evidence.split(','));renderPreferenceEvidence(preferenceEvidence.filter(p=>ids.has(String(p.post_id))))};preferenceRatings(ratings)}

function switching(items){const svg=$('#switchChart');svg.innerHTML='';const flows=Object.entries(items||{}).map(([pair,count])=>({pair,count})),H=Math.max(430,80+flows.length*86);svg.setAttribute('viewBox',`0 0 1180 ${H}`);svg.style.height=`${H}px`;if(!flows.length){addText(svg,590,215,'No verified switches','svg-value','middle');return}flows.forEach((f,i)=>{const [from,to]=f.pair.split(' -> '),y=65+i*86,count=f.count;svg.append(el('rect',{x:65,y:y-21,width:250,height:42,class:'node'}));addText(svg,190,y+5,label(from),'node-label','middle');svg.append(el('path',{d:`M 315 ${y} C 490 ${y}, 690 ${y+25*(i%2?1:-1)}, 865 ${y}`,class:'flow','stroke-width':6+count*3}));svg.append(el('rect',{x:865,y:y-21,width:250,height:42,class:'node'}));addText(svg,990,y+5,label(to),'node-label','middle');addText(svg,590,y-13,`${count} verified`,'svg-label','middle')})}

function harness(data){const s=data.strict||{},v=s.votes||{},rows=data.sentiment||[],sentimentRows=rows.map(m=>{const c=m.clean_directional||{},n=c.n||0,delta=m.latest_24h_delta_points,dc=delta==null||delta===0?'neutral':delta>0?'positive':'negative';return`<div class="harness-sentiment-row"><header><span>${label(m.model)}</span><strong>${n} expressed</strong></header><div><span class="positive" style="width:${n?c.positive/n*100:0}%"></span><span class="mixed" style="width:${n?c.mixed/n*100:0}%"></span><span class="negative" style="width:${n?c.negative/n*100:0}%"></span></div><b class="${dc}">${delta==null?'—':`${delta>0?'+':''}${delta}`}</b></div>`}).join('');$('#harnessAttention').innerHTML=`<p class="duel-title">// sentiment</p>${sentimentRows||'<p class="duel-copy">No expressed harness sentiment in this window.</p>'}`;$('#harnessPreference').innerHTML=`<p class="duel-title">// direct head-to-head</p><div class="preference-big">${v.claude_code||0}—${v.codex||0}</div><strong>Claude Code / Codex</strong><p>${s.n||0} direct comparisons across seven days.</p><div class="chooser-result"><span>verified switches</span><strong>${data.switches?.n||0}</strong><small>kept separate from preference</small></div>`}

function quality(){return}

let preferenceEvidence=[];
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const evidenceCard=(p,kind='preference')=>{const verdict=kind==='preference'?`${label(p.winner)} > ${label(p.loser)}`:kind==='switching'?`${label(p.origin)} → ${label(p.destination)}`:kind==='harness'?`${label(p.winner)} preferred`:`${label(p.model)} · ${p.sentiment}`;return`<a class="counted-tweet" href="${p.url}" target="_blank" rel="noreferrer"><header><i class="avatar-fallback"></i><span><b>X post</b><small>${new Date(p.created_at).toLocaleString()}</small></span></header><p>${esc(p.text)}</p><footer><span>${esc(verdict)}</span></footer><span class="open" aria-hidden="true">↗</span></a>`};
function renderPreferenceEvidence(records){const html=records.map(p=>evidenceCard(p)).join('')||'<div class="evidence-empty">No adjudicated preference evidence.</div>';$('#battleEvidence').innerHTML=html}
function countedEvidence(data){preferenceEvidence=data.preference||[];renderPreferenceEvidence(preferenceEvidence);$('#ratingEvidence').innerHTML=preferenceEvidence.map(p=>evidenceCard(p)).join('')||'<div class="evidence-empty">No adjudicated preference evidence.</div>'}

function evidence(data){const root=$('#muralGrid'),posts=[...(data.preference||[]),...(data.switching||[]),...(data.harness||[]),...(data.harness_sentiment||[]),...(data.harness_switching||[]),...(data.sentiment||[])];if(!posts.length){root.innerHTML='<p class="mural-loading">The conversation is quiet.</p>';return}const card=(p,i,enter=false)=>{const axis=i%2?'flip-x':'flip-y';return`<a class="mural-card ${axis}${enter?' is-entering':''}" href="${p.url}" target="_blank" rel="noreferrer"><header><i class="avatar-fallback"></i><span><b>X post</b><small>${new Date(p.created_at).toLocaleString()}</small></span></header><p>${esc(p.text)}</p><span class="mural-open" aria-hidden="true">↗</span><em>[ XBENCH / EVIDENCE ]</em></a>`};root.innerHTML=posts.slice(0,6).map((p,i)=>card(p,i)).join('');if(!matchMedia('(prefers-reduced-motion: reduce)').matches&&posts.length>6){let cursor=6;setInterval(()=>{const cells=[...root.children],i=cursor%cells.length,current=cells[i];current.classList.add('is-flipping');setTimeout(()=>{current.outerHTML=card(posts[cursor%posts.length],i,true);cursor++},260)},3400)}}

async function init(){heroMesh();quality();try{const embedded=window.XBENCH_DATA;document.documentElement.dataset.dataSource=embedded?'embedded':'json';const [summary,ev]=embedded?[embedded.summary,embedded.evidence]:await Promise.all([fetch('data/agent-rebuild/public-summary.json').then(r=>r.json()),fetch('data/agent-rebuild/public-evidence.json').then(r=>r.json())]),corpus=summary.corpus||{},w=summary.window||{};$('#statPosts').textContent=fmt(corpus.unique_posts);$('#statAuthors').textContent=fmt(corpus.unique_authors);$('#statComments').textContent=fmt(corpus.comments);$('#statSpend').textContent=`$${Number(summary.recorded_spend_usd||0).toFixed(2)}`;$('#heroWindow').textContent=`${new Date(w.start).toLocaleString()} → ${new Date(w.end).toLocaleString()}`;$('#surfaceValue').textContent=fmt(corpus.unique_posts);attentionChart(summary.attention.models);sentiment(summary.sentiment.models);countedEvidence(ev);battles(summary.preference.head_to_head,summary.preference.xbenchpref.ratings);switching(summary.switching.by_origin_destination);$('#switchingCount').textContent=`${summary.switching.verified_completed_switches} observed`;$('#switchingTrend').textContent=`24h ${summary.switching.latest_24h_change>=0?'+':''}${summary.switching.latest_24h_change}`;harness(summary.harnesses);evidence(ev)}catch(err){console.error(err);document.body.classList.add('data-error');$('#heroWindow').textContent='local data could not load';$('#surfaceValue').textContent='ERR'}}init();
